language: generic
os: linux
dist: trusty
sudo: required
services:
  - docker

# Required environment variables:
# DOCKER_USERNAME: the username of the Docker Hub account used to push images
# DOCKER_PASSWORD: base64-encoded password of the Docker Hub user

matrix:
  include:
    - env: TASK=lint
    - env: TASK=build
      if: branch = master OR type = cron

script: |
  if [[ -x "ci/${TASK}.sh" ]]; then
      bash "ci/${TASK}.sh"
  else
      echo "Error: missing run script for task ${TASK}"
      exit 1
  fi
