version: 1.0.{build}
image: Visual Studio 2017

platform:
    - x86

environment:
    PUSH_IMAGE: 'rustops/crates-build-env-windows'

# If Docker is currently configured to run Linux containers, we need to switch
# to running Windows containers.
#
# https://github.com/docker/cli/issues/1042
init:
    # - ps: $env:ProgramFiles/Docker/Docker/DockerCli.exe -SwitchDaemon

build_script:
    - ps: ./windows/ci/build.ps1

deploy_script:
    - ps: if ($env:APPVEYOR_REPO_BRANCH -eq "master") { ./windows/ci/publish.ps1 }

